const mongoose = require('mongoose');

// TODO(security): Ensure database user for this application has least-privilege
// permissions (no DROP/DELETE unless required) per the secure coding guidelines.

const paymentSchema = new mongoose.Schema(
    {
        studentId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
            index: true
        },

        classId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Class',
            required: true,
            index: true
        },

        amount: {
            type: Number,
            required: true,
            min: 0
        },

        currency: {
            type: String,
            default: 'LKR',
            uppercase: true,
            trim: true
        },

        // Payment lifecycle: initiated -> pending -> completed | failed | cancelled
        status: {
            type: String,
            enum: ['initiated', 'pending', 'completed', 'failed', 'cancelled'],
            default: 'initiated',
            index: true
        },

        // Unique order identifier generated by this system
        orderId: {
            type: String,
            required: true,
            unique: true,
            trim: true
        },

        // Transaction identifier returned by the payment gateway
        // TODO(security): Do NOT log or expose transactionId in client-facing
        // error messages to prevent information leakage.
        transactionId: {
            type: String,
            trim: true,
            default: null
        },

        paidAt: {
            type: Date,
            default: null
        }
    },
    {
        timestamps: true  // adds createdAt and updatedAt automatically
    }
);

module.exports = mongoose.model('Payment', paymentSchema);
